/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as MasterRouteImport } from './routes/master'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterPainelRouteImport } from './routes/master/painel'
import { Route as MasterNovaEmpresaRouteImport } from './routes/master/nova-empresa'
import { Route as MasterEmpresasRouteImport } from './routes/master/empresas'
import { Route as MasterConfiguracoesRouteImport } from './routes/master/configuracoes'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as DemoCrmRouteImport } from './routes/demo/crm'
import { Route as DemoConversasRouteImport } from './routes/demo/conversas'
import { Route as DemoAgenteRouteImport } from './routes/demo/agente'
import { Route as AppRelatoriosRouteImport } from './routes/app/relatorios'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppEquipeRouteImport } from './routes/app/equipe'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppCrmRouteImport } from './routes/app/crm'
import { Route as AppConversasRouteImport } from './routes/app/conversas'
import { Route as AppContatosRouteImport } from './routes/app/contatos'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppConexaoRouteImport } from './routes/app/conexao'
import { Route as AppAgenteRouteImport } from './routes/app/agente'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google-callback'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPainelRoute = MasterPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => MasterRoute,
} as any)
const MasterNovaEmpresaRoute = MasterNovaEmpresaRouteImport.update({
  id: '/nova-empresa',
  path: '/nova-empresa',
  getParentRoute: () => MasterRoute,
} as any)
const MasterEmpresasRoute = MasterEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterConfiguracoesRoute = MasterConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MasterRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCrmRoute = DemoCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConversasRoute = DemoConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAgenteRoute = DemoAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => DemoRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppConversasRoute = AppConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConexaoRoute = AppConexaoRouteImport.update({
  id: '/conexao',
  path: '/conexao',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google-callback',
  path: '/api/public/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/conexao': typeof AppConexaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/demo/agente': typeof DemoAgenteRoute
  '/demo/conversas': typeof DemoConversasRoute
  '/demo/crm': typeof DemoCrmRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/nova-empresa': typeof MasterNovaEmpresaRoute
  '/master/painel': typeof MasterPainelRoute
  '/api/public/google-callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/conexao': typeof AppConexaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/demo/agente': typeof DemoAgenteRoute
  '/demo/conversas': typeof DemoConversasRoute
  '/demo/crm': typeof DemoCrmRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/nova-empresa': typeof MasterNovaEmpresaRoute
  '/master/painel': typeof MasterPainelRoute
  '/api/public/google-callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/conexao': typeof AppConexaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/demo/agente': typeof DemoAgenteRoute
  '/demo/conversas': typeof DemoConversasRoute
  '/demo/crm': typeof DemoCrmRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/nova-empresa': typeof MasterNovaEmpresaRoute
  '/master/painel': typeof MasterPainelRoute
  '/api/public/google-callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/agente'
    | '/app/conexao'
    | '/app/configuracoes'
    | '/app/contatos'
    | '/app/conversas'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/demo/agente'
    | '/demo/conversas'
    | '/demo/crm'
    | '/demo/dashboard'
    | '/master/configuracoes'
    | '/master/empresas'
    | '/master/nova-empresa'
    | '/master/painel'
    | '/api/public/google-callback'
    | '/api/public/whatsapp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/agente'
    | '/app/conexao'
    | '/app/configuracoes'
    | '/app/contatos'
    | '/app/conversas'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/demo/agente'
    | '/demo/conversas'
    | '/demo/crm'
    | '/demo/dashboard'
    | '/master/configuracoes'
    | '/master/empresas'
    | '/master/nova-empresa'
    | '/master/painel'
    | '/api/public/google-callback'
    | '/api/public/whatsapp-webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/agente'
    | '/app/conexao'
    | '/app/configuracoes'
    | '/app/contatos'
    | '/app/conversas'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/demo/agente'
    | '/demo/conversas'
    | '/demo/crm'
    | '/demo/dashboard'
    | '/master/configuracoes'
    | '/master/empresas'
    | '/master/nova-empresa'
    | '/master/painel'
    | '/api/public/google-callback'
    | '/api/public/whatsapp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  MasterRoute: typeof MasterRouteWithChildren
  ResetSenhaRoute: typeof ResetSenhaRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/painel': {
      id: '/master/painel'
      path: '/painel'
      fullPath: '/master/painel'
      preLoaderRoute: typeof MasterPainelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/nova-empresa': {
      id: '/master/nova-empresa'
      path: '/nova-empresa'
      fullPath: '/master/nova-empresa'
      preLoaderRoute: typeof MasterNovaEmpresaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/empresas': {
      id: '/master/empresas'
      path: '/empresas'
      fullPath: '/master/empresas'
      preLoaderRoute: typeof MasterEmpresasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/configuracoes': {
      id: '/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof MasterConfiguracoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/crm': {
      id: '/demo/crm'
      path: '/crm'
      fullPath: '/demo/crm'
      preLoaderRoute: typeof DemoCrmRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/conversas': {
      id: '/demo/conversas'
      path: '/conversas'
      fullPath: '/demo/conversas'
      preLoaderRoute: typeof DemoConversasRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/agente': {
      id: '/demo/agente'
      path: '/agente'
      fullPath: '/demo/agente'
      preLoaderRoute: typeof DemoAgenteRouteImport
      parentRoute: typeof DemoRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversas': {
      id: '/app/conversas'
      path: '/conversas'
      fullPath: '/app/conversas'
      preLoaderRoute: typeof AppConversasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contatos': {
      id: '/app/contatos'
      path: '/contatos'
      fullPath: '/app/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conexao': {
      id: '/app/conexao'
      path: '/conexao'
      fullPath: '/app/conexao'
      preLoaderRoute: typeof AppConexaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agente': {
      id: '/app/agente'
      path: '/agente'
      fullPath: '/app/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-callback': {
      id: '/api/public/google-callback'
      path: '/api/public/google-callback'
      fullPath: '/api/public/google-callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgenteRoute: typeof AppAgenteRoute
  AppConexaoRoute: typeof AppConexaoRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppConversasRoute: typeof AppConversasRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenteRoute: AppAgenteRoute,
  AppConexaoRoute: AppConexaoRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppConversasRoute: AppConversasRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAgenteRoute: typeof DemoAgenteRoute
  DemoConversasRoute: typeof DemoConversasRoute
  DemoCrmRoute: typeof DemoCrmRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAgenteRoute: DemoAgenteRoute,
  DemoConversasRoute: DemoConversasRoute,
  DemoCrmRoute: DemoCrmRoute,
  DemoDashboardRoute: DemoDashboardRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterConfiguracoesRoute: typeof MasterConfiguracoesRoute
  MasterEmpresasRoute: typeof MasterEmpresasRoute
  MasterNovaEmpresaRoute: typeof MasterNovaEmpresaRoute
  MasterPainelRoute: typeof MasterPainelRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterConfiguracoesRoute: MasterConfiguracoesRoute,
  MasterEmpresasRoute: MasterEmpresasRoute,
  MasterNovaEmpresaRoute: MasterNovaEmpresaRoute,
  MasterPainelRoute: MasterPainelRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  MasterRoute: MasterRouteWithChildren,
  ResetSenhaRoute: ResetSenhaRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
